
# FROM node:14

# WORKDIR /app

# COPY /package*.json ./

# RUN npm install

# COPY  . ./

# EXPOSE 8080

# CMD [ "npm", "run", "serve" ]



FROM node:14-alpine AS build


WORKDIR /app


COPY package*.json ./


RUN npm install


COPY . .


RUN npm run build


FROM nginx:alpine


COPY --from=build /app/dist /usr/share/nginx/html


COPY .env.example /usr/share/nginx/html


EXPOSE 80

# Start the nginx web server
CMD ["nginx", "-g", "daemon off;"]
