# FROM node:lts-alpine


# RUN npm install -g http-server

# WORKDIR /app

# COPY package*.json ./

# RUN npm install

# COPY . .
# COPY frontend.env ./.env

# RUN npm run build

# EXPOSE 8080
# CMD [ "http-server", "dist" ]


# Stage 1: Build stage
# FROM node:lts-alpine as build

# RUN npm install -g http-server
# WORKDIR /app

# COPY package*.json ./
# RUN npm install

# COPY . .
# COPY frontend.env ./.env

# RUN npm run build

# # Stage 2: Production stage
# FROM node:lts-alpine

# WORKDIR /app

# COPY --from=build /app/dist /app

# EXPOSE 8080
# CMD ["http-server", "."]

FROM node:lts-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
COPY frontend.env ./.env
RUN npm run build

EXPOSE 8080
CMD ["npm", "run", "serve"]

