# Use a lightweight base image
FROM golang:1.17-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy go.mod and go.sum files to the container
COPY go.mod ./
COPY go.sum ./

# Download Go module dependencies
RUN go mod download

# Copy all source files to the container
COPY . ./

# Build the Go application
RUN go build -o main

# Expose port 5000 for the application
EXPOSE 5000

# Command to run the application
CMD ["./main"]

